# Generated by Django 4.2.4 on 2023-08-08 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_address_remove_project_address_project_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='address',
        ),
    ]
